### ISSUE TITLE
Sorry need your help 

### ISSUE THREAD

**Issue by atplsx** [jborean93/PSDetour#4]

**Comment by jborean93** [comment]
You can use something like this https://gist.github.com/jborean93/6c1f1b3130f2675f1618da56633eb1fa to generate the `SSLKEYLOGFILE` that Wireshark can use to decrypt TLS traffic to capture what you need. Anything else is dependent on you knowing what API to hook and implementing it.

**Comment by atplsx** [comment]
Thank you for help

**Comment by atplsx** [comment]
I try but didn't work. Wireshark very complicated. Is there a way to do it with fiddler? actually i can do this with fiddler but the process fails because windows update gives ssl certificate error. I can't see all the traffic just until one point

**Comment by jborean93** [comment]
These are all questions unrelated to this module, I can't really help you here.

**Comment by atplsx** [comment]
Ok thank you I posted it here because I thought you might be able to help.
